// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3KTfd8KHoaiDdnItztdRxtZkAbu3JH4I',
    appId: '1:378212041125:web:4458e1a979978c7a81684c',
    messagingSenderId: '378212041125',
    projectId: 'flutter-firebase-66b04',
    authDomain: 'flutter-firebase-66b04.firebaseapp.com',
    storageBucket: 'flutter-firebase-66b04.appspot.com',
    measurementId: 'G-VV4X7NJR7Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGGb6FrqJQD-ICCt8nviCsrdpNCNSyncE',
    appId: '1:378212041125:android:7275aa1b53060cf481684c',
    messagingSenderId: '378212041125',
    projectId: 'flutter-firebase-66b04',
    storageBucket: 'flutter-firebase-66b04.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhI74ozi7LkKvpZr82Nqw5OtDkxsF2jjQ',
    appId: '1:378212041125:ios:dd6a92c8c901d71e81684c',
    messagingSenderId: '378212041125',
    projectId: 'flutter-firebase-66b04',
    storageBucket: 'flutter-firebase-66b04.appspot.com',
    iosClientId: '378212041125-f34g7frsvu6nbfr6t8arke30lfcnk43k.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBhI74ozi7LkKvpZr82Nqw5OtDkxsF2jjQ',
    appId: '1:378212041125:ios:dd6a92c8c901d71e81684c',
    messagingSenderId: '378212041125',
    projectId: 'flutter-firebase-66b04',
    storageBucket: 'flutter-firebase-66b04.appspot.com',
    iosClientId: '378212041125-f34g7frsvu6nbfr6t8arke30lfcnk43k.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFirebase',
  );
}
